# Generated by Django 6.0.1 on 2026-01-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_can_edit"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_manage_payments",
            field=models.BooleanField(
                default=False, help_text="Whether this staff member can manage payments"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="can_manage_students",
            field=models.BooleanField(
                default=False, help_text="Whether this staff member can manage students"
            ),
        ),
    ]
