# Generated by Django 5.0.1 on 2026-02-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0002_alter_feestructure_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="default_batch_timing",
            field=models.CharField(
                default="7-8 AM",
                help_text="Default batch timing for this subject",
                max_length=50,
            ),
        ),
    ]
