# Generated by Django 5.0.1 on 2026-02-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0003_subject_default_batch_timing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feestructure",
            name="duration",
            field=models.CharField(
                choices=[("1_MONTH", "1 Month"), ("3_MONTHS", "3 Months")],
                default="1_MONTH",
                max_length=20,
            ),
        ),
    ]
