# Generated by Django 6.0.1 on 2026-01-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_edit",
            field=models.BooleanField(
                default=False,
                help_text="Whether this staff member has edit permissions",
            ),
        ),
    ]
