# Generated by Django 6.0.1 on 2026-02-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_remove_loginotp_login_otps_email_ebaa7a_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True, help_text="User full name", max_length=255
            ),
        ),
    ]
