# Generated by Django 6.0.1 on 2026-02-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_user_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refreshtoken",
            name="token",
            field=models.CharField(
                help_text="Refresh token string", max_length=2000, unique=True
            ),
        ),
    ]
