# Generated by Django 6.0.2 on 2026-04-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0010_remove_user_can_edit_remove_user_can_manage_payments_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_authorized",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user is authorized to use the system",
            ),
        ),
    ]
