# Generated by Django 6.0.2 on 2026-04-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0011_user_is_authorized"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Email address (optional, can be used by multiple users)",
                max_length=254,
                null=True,
            ),
        ),
    ]
