# Generated by Django 6.0.1 on 2026-01-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="login_password_hint",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="login_username",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
