# Generated by Django 5.0.1 on 2026-02-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_alter_student_age_alter_student_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
