# Generated by Django 5.0.1 on 2026-02-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0008_alter_student_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="area",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
