# Generated by Django 6.0.1 on 2026-02-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_alter_student_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                help_text="Blood group for ID card",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Student email for notifications",
                max_length=254,
                null=True,
            ),
        ),
    ]
