# Generated by Django 5.0.1 on 2026-02-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_alter_feestructure_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='activity_type',
            field=models.CharField(choices=[('SUMMER_CAMP', 'Summer Camp'), ('YEAR_ROUND', 'Year-Round Activity')], default='SUMMER_CAMP', help_text='Type of activity - Summer Camp or Year-Round', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='duration_months',
            field=models.IntegerField(blank=True, help_text='Course duration in months (for year-round activities)', null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='monthly_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly fee for year-round activities', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='timing_schedule',
            field=models.CharField(blank=True, help_text='Class timing schedule (e.g., "Mon & Fri 5 PM - 6 PM")', max_length=200),
        ),
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('EDUCATION', 'Education'), ('MUSIC', 'Music'), ('ART', 'Art'), ('SPORTS', 'Sports'), ('DANCE', 'Dance'), ('COMPUTER', 'Computer'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
