# Generated by Django 6.0.2 on 2026-04-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0007_subject_age_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="default_batch_timing",
            field=models.CharField(
                default="7-8 AM",
                help_text="Default batch timing for this subject",
                max_length=200,
            ),
        ),
    ]
