# Generated by Django 6.0.2 on 2026-04-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0008_alter_subject_default_batch_timing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feestructure",
            name="duration",
            field=models.CharField(
                choices=[("1_MONTH", "1 Month")], default="1_MONTH", max_length=20
            ),
        ),
    ]
