# Generated by Django 6.0.1 on 2026-01-28 06:36

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrollment_id",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated enrollment ID",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("enrollment_date", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("DROPPED", "Dropped"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "total_fee",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total fee for this enrollment",
                        max_digits=10,
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total amount paid",
                        max_digits=10,
                    ),
                ),
                (
                    "pending_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Pending amount to be paid",
                        max_digits=10,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="students.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "db_table": "enrollments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["enrollment_id"], name="enrollments_enrollm_6154fe_idx"
                    ),
                    models.Index(
                        fields=["student", "status"],
                        name="enrollments_student_929bef_idx",
                    ),
                ],
                "unique_together": {("student", "subject")},
            },
        ),
    ]
