# Generated by Django 5.0.1 on 2026-02-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="batch_time",
            field=models.CharField(
                choices=[
                    ("7-8 AM", "7-8 AM (Morning)"),
                    ("8-9 AM", "8-9 AM (Morning)"),
                    ("5-6 PM", "5-6 PM (Evening)"),
                    ("6-7 PM", "6-7 PM (Evening)"),
                ],
                default="7-8 AM",
                help_text="Batch timing for the subject",
                max_length=20,
            ),
        ),
    ]
