# Generated by Django 5.0.1 on 2026-02-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0002_enrollment_batch_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="include_library_fee",
            field=models.BooleanField(
                default=False,
                help_text="Whether library fee (₹10) is included for this enrollment",
            ),
        ),
    ]
