# Generated by Django 6.0.2 on 2026-03-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0003_enrollment_include_library_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
