# Generated by Django 6.0.2 on 2026-04-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0005_enrollment_id_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="batch_time",
            field=models.CharField(
                default="7-8 AM",
                help_text="Batch timing for the subject",
                max_length=20,
            ),
        ),
    ]
