# Generated by Django 6.0.2 on 2026-04-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0007_alter_enrollment_batch_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="roll_number",
            field=models.IntegerField(
                blank=True, help_text="Subject-wise roll number (1, 2, 3...)", null=True
            ),
        ),
    ]
