# Generated by Django 6.0.1 on 2026-02-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_payment_cheque_number_payment_razorpay_order_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_CONFIRMATION", "Pending Confirmation"),
                    ("CREATED", "Created"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                ],
                default="SUCCESS",
                help_text="Payment status - PENDING_CONFIRMATION for cash/cheque awaiting admin confirmation, CREATED for pending online, SUCCESS for completed, FAILED for failed",
                max_length=25,
            ),
        ),
    ]
