# Generated by Django 5.0.1 on 2026-02-05 06:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_alter_payment_receipt_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_time",
            field=models.TimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Time when payment was recorded",
            ),
            preserve_default=False,
        ),
    ]
