# Generated by Django 5.0.1 on 2026-02-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_payment_installment_number_payment_is_installment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="cheque_number",
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_mode",
            field=models.CharField(
                choices=[("CASH", "Cash"), ("ONLINE", "Online")],
                default="CASH",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_CONFIRMATION", "Pending Confirmation"),
                    ("CREATED", "Created"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                ],
                default="SUCCESS",
                help_text="Payment status - PENDING_CONFIRMATION for cash/offline awaiting admin confirmation, CREATED for pending online, SUCCESS for completed, FAILED for failed",
                max_length=25,
            ),
        ),
    ]
