# Generated by Django 6.0.2 on 2026-04-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0006_subject_max_seats"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="age_limit",
            field=models.CharField(
                blank=True,
                help_text='Age group/limit for this subject (e.g. "4 to 16")',
                max_length=100,
            ),
        ),
    ]
