# Generated by Django 6.0.2 on 2026-04-10 12:26

from django.db import migrations


def fix_pencil_batch(apps, schema_editor):
    Subject = apps.get_model('subjects', 'Subject')
    q = Subject.objects.filter(name__icontains='pencil')
    for s in q:
        s.default_batch_timing = '5:00 PM - 6:00 PM'
        s.save()

class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0009_alter_feestructure_duration"),
    ]

    operations = [
        migrations.RunPython(fix_pencil_batch),
    ]

