# Generated by Django 6.0.2 on 2026-04-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0010_fix_pencil_batch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="activity_type",
            field=models.CharField(
                choices=[("SUMMER_CAMP", "Summer Camp")],
                default="SUMMER_CAMP",
                help_text="Type of activity - Summer Camp or Year-Round",
                max_length=20,
            ),
        ),
    ]
