# Generated by Django 6.0.2 on 2026-04-15 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0011_alter_subject_activity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="activity_type",
            field=models.CharField(
                choices=[("SUMMER_CAMP", "Summer Camp")],
                default="SUMMER_CAMP",
                help_text="Type of activity",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SubjectBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_time",
                    models.CharField(
                        help_text='Batch timing (e.g., "Batch A: 7:00 AM - 8:00 AM")',
                        max_length=200,
                    ),
                ),
                (
                    "capacity_limit",
                    models.IntegerField(
                        default=50,
                        help_text="Maximum number of students for this batch",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_configs",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "db_table": "subject_batches",
                "ordering": ["subject", "batch_time"],
                "unique_together": {("subject", "batch_time")},
            },
        ),
    ]
