# Generated by Django 6.0.1 on 2026-02-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_user_can_manage_payments_user_can_manage_students"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="User email address (used for login)",
                max_length=254,
                null=True,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="LoginOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address to which OTP was sent", max_length=254
                    ),
                ),
                (
                    "otp_code",
                    models.CharField(help_text="6-digit OTP code", max_length=6),
                ),
                ("expires_at", models.DateTimeField(help_text="When the OTP expires")),
                (
                    "is_used",
                    models.BooleanField(
                        default=False, help_text="Whether this OTP has been used"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "login_otps",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "otp_code", "is_used"],
                        name="login_otps_email_ebaa7a_idx",
                    )
                ],
            },
        ),
    ]
