# Generated by Django 6.0.1 on 2026-02-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_user_email_loginotp"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="loginotp",
            name="login_otps_email_ebaa7a_idx",
        ),
        migrations.DeleteModel(
            name="LoginOTP",
        ),
        migrations.AddField(
            model_name="user",
            name="notify_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_sms",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_whatsapp",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
