# Generated by Django 6.0.2 on 2026-03-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_alter_refreshtoken_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("STAFF", "Staff"),
                    ("STUDENT", "Student"),
                    ("ACCOUNTANT", "Accountant"),
                ],
                default="STUDENT",
                help_text="User role for access control",
                max_length=10,
            ),
        ),
    ]
