# Generated by Django 6.0.2 on 2026-03-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_view_analytics",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="can_view_dashboard",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="can_view_enrollments",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="can_view_payments",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="can_view_registration_requests",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="can_view_reports",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="can_view_settings",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="can_view_students",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="can_view_subjects",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="can_view_users",
            field=models.BooleanField(default=False),
        ),
    ]
