# Generated by Django 6.0.2 on 2026-03-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0009_user_can_view_analytics_user_can_view_dashboard_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="can_edit",
        ),
        migrations.RemoveField(
            model_name="user",
            name="can_manage_payments",
        ),
        migrations.RemoveField(
            model_name="user",
            name="can_manage_students",
        ),
        migrations.AddField(
            model_name="user",
            name="is_two_factor_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_view_dashboard",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_view_settings",
            field=models.BooleanField(default=False),
        ),
    ]
