# Generated by Django 6.0.1 on 2026-02-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_payment_payment_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="cheque_number",
            field=models.CharField(
                blank=True, help_text="Cheque number for cheque payments", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="razorpay_order_id",
            field=models.CharField(
                blank=True,
                help_text="Razorpay order ID for online payments",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="razorpay_payment_id",
            field=models.CharField(
                blank=True,
                help_text="Razorpay payment ID for online payments",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="razorpay_signature",
            field=models.CharField(
                blank=True,
                help_text="Razorpay signature for payment verification",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                ],
                default="SUCCESS",
                help_text="Payment status - CREATED for pending, SUCCESS for completed, FAILED for failed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_mode",
            field=models.CharField(
                choices=[("CASH", "Cash"), ("CHEQUE", "Cheque"), ("ONLINE", "Online")],
                default="CASH",
                max_length=20,
            ),
        ),
    ]
