# Generated by Django 5.0.1 on 2026-02-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_payment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='installment_number',
            field=models.IntegerField(blank=True, help_text='Installment number for partial payments (1st, 2nd, 3rd, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_installment',
            field=models.BooleanField(default=False, help_text='Whether this is an installment payment'),
        ),
    ]
