# Generated by Django 6.0.2 on 2026-04-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0005_subject_activity_type_subject_duration_months_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="max_seats",
            field=models.IntegerField(
                default=50, help_text="Maximum number of students for this subject"
            ),
        ),
    ]
