# Generated by Django 6.0.2 on 2026-04-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0014_subjectbatch_auto_close_when_full"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="class_mode",
            field=models.CharField(
                choices=[
                    ("ONLINE", "Online"),
                    ("OFFLINE", "Offline"),
                    ("BOTH", "Both Online & Offline"),
                ],
                default="BOTH",
                help_text="Mode of instruction: Online, Offline, or Both",
                max_length=20,
            ),
        ),
    ]
