# Generated by Django 6.0.1 on 2026-02-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_student_blood_group_student_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Student photo for ID card",
                null=True,
                upload_to="student_photos/",
            ),
        ),
    ]
