# Generated by Django 6.0.2 on 2026-03-24 10:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0011_alter_student_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="photo",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Student photo for ID card",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="studentregistrationrequest",
            name="photo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
