# Generated by Django 6.0.2 on 2026-04-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0012_alter_student_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="pincode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="studentregistrationrequest",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="studentregistrationrequest",
            name="pincode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
