# Generated by Django 6.0.1 on 2026-01-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_mode",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("UPI", "UPI"),
                    ("BANK", "Bank Transfer"),
                    ("CARD", "Card"),
                    ("CHEQUE", "Cheque"),
                    ("RAZORPAY", "Razorpay Online"),
                ],
                default="CASH",
                max_length=20,
            ),
        ),
    ]
