# Generated by Django 6.0.2 on 2026-03-24 09:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0009_feeledgerentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="receipt_pdf",
            field=cloudinary.models.CloudinaryField(
                blank=True, help_text="Stored receipt PDF", max_length=255, null=True
            ),
        ),
    ]
