# Generated by Django 6.0.2 on 2026-04-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_payment_receipt_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="receipt_pdf",
            field=models.FileField(
                blank=True,
                help_text="Stored receipt PDF",
                null=True,
                upload_to="receipts/",
            ),
        ),
    ]
