# Generated by Django 6.0.2 on 2026-04-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0011_alter_payment_receipt_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="receipt_number",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Auto-generated receipt number - shared by all payments of same student",
                max_length=20,
                null=True,
            ),
        ),
    ]
