# Generated by Django 6.0.2 on 2026-03-24 09:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0004_alter_enrollment_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="id_card",
            field=cloudinary.models.CloudinaryField(
                blank=True, help_text="Stored ID card PDF", max_length=255, null=True
            ),
        ),
    ]
