# Generated by Django 6.0.2 on 2026-04-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0008_enrollment_roll_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="id_card",
            field=models.FileField(
                blank=True,
                help_text="Stored ID card PDF",
                null=True,
                upload_to="id_cards/",
            ),
        ),
    ]
